/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.modelCustomer;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import model.modelSql;

/**
 *
 * @author asass
 */
public class viewCustomerInsert extends javax.swing.JFrame {

    /**
     * Creates new form supplierInsert
     */
    public viewCustomerInsert() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        setTitle("Insert Customer Data");
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jcustomer = new javax.swing.JLabel();
        jpenanggungjawab = new javax.swing.JLabel();
        jtelepon = new javax.swing.JLabel();
        jalamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        namacustomer = new javax.swing.JTextField();
        penanggungjawab = new javax.swing.JTextField();
        telepon = new javax.swing.JTextField();
        insertbutton = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcustomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcustomer.setText("Nama Customer");

        jpenanggungjawab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpenanggungjawab.setText("Penanggung Jawab");

        jtelepon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtelepon.setText("Telepon");

        jalamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jalamat.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        namacustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namacustomerActionPerformed(evt);
            }
        });

        insertbutton.setText("Insert");
        insertbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttonActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Input Data Customer Baru");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Fax");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcustomer)
                    .addComponent(jpenanggungjawab)
                    .addComponent(jtelepon)
                    .addComponent(jLabel2)
                    .addComponent(jalamat))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fax)
                    .addComponent(namacustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(penanggungjawab)
                    .addComponent(telepon)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namacustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penanggungjawab, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jpenanggungjawab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtelepon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(insertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jalamat)))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namacustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namacustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namacustomerActionPerformed

    private void insertbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttonActionPerformed
        // TODO add your handling code here:
        modelCustomer insert = new modelCustomer();
        String Nama = namacustomer.getText();
        String Alamat = alamat.getText();
        String PenanggungJawab = penanggungjawab.getText();
        String Telepon = telepon.getText();
        String Fax = fax.getText();
        
        insert.setNamaCustomer(Nama);
        insert.setAlamat(Alamat);
        insert.setTelepon(Telepon);
        insert.setPenanggungJawab(PenanggungJawab);
        insert.setFax(Fax);
        insert(insert.getNamaCustomer(), insert.getAlamat(), insert.getPenanggungJawab(), insert.getTelepon(), insert.getFax());  
    }//GEN-LAST:event_insertbuttonActionPerformed

    public void insert(String varnama, String varalamat, String varpenanggungjawab, String vartelepon, String varfax)
    {
        if(namacustomer.getText().length() >= 30)
        {
            JOptionPane.showMessageDialog(null, "Panjang Nama Maksimal 30 Huruf");
        }
        else if(alamat.getText().length() >= 30)
        {
            JOptionPane.showMessageDialog(null, "Panjang Nama Maksimal 30 Huruf");
        }
        else if(penanggungjawab.getText().length() >= 30)
        {
            JOptionPane.showMessageDialog(null, "Panjang Nama Maksimal 30 Huruf");
        }
        else if(telepon.getText().length() >= 12)
        {
            JOptionPane.showMessageDialog(null, "Panjang nomor telepon maksimal adalah 13 angka");
        }
        else if(fax.getText().length() >= 12)
        {
            JOptionPane.showMessageDialog(null, "Panjang FAX maksimal adalah 13 angka");
        }
        
        else if(namacustomer.getText().length() == 0 || alamat.getText().length() == 0 || penanggungjawab.getText().length() == 0 || telepon.getText().length() == 0 || fax.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Semua Kolom Harus Diisi");
        }
        else
        {
            try
            {
                PreparedStatement st;

                st = modelSql.getKoneksi().prepareStatement("INSERT INTO customer(NamaCustomer, Alamat, PenanggungJawab, Telepon, Fax) VALUES('"+varnama+"', '"+varalamat+"', '"+varpenanggungjawab+"', '"+vartelepon+"', '"+varfax+"')");
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukan");
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton close;
    private javax.swing.JTextField fax;
    private javax.swing.JButton insertbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jalamat;
    private javax.swing.JLabel jcustomer;
    private javax.swing.JLabel jpenanggungjawab;
    private javax.swing.JLabel jtelepon;
    private javax.swing.JTextField namacustomer;
    private javax.swing.JTextField penanggungjawab;
    private javax.swing.JTextField telepon;
    // End of variables declaration//GEN-END:variables
}
