/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controllerSupplier;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import model.modelSupplier;
import model.modelSql;

/**
 *
 * @author asass
 */
public class viewSupplierInsert extends javax.swing.JFrame {

    /**
     * Creates new form supplierInsert
     */
    public viewSupplierInsert() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        setTitle("Insert Supplier Data");
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsupplier = new javax.swing.JLabel();
        jpenanggungjawab = new javax.swing.JLabel();
        jkontak = new javax.swing.JLabel();
        jalamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        namasupplier = new javax.swing.JTextField();
        penanggungjawab = new javax.swing.JTextField();
        kontak = new javax.swing.JTextField();
        insertbutton = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsupplier.setText("Nama Supplier");

        jpenanggungjawab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpenanggungjawab.setText("Penanggung Jawab");

        jkontak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jkontak.setText("Kontak");

        jalamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jalamat.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        namasupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namasupplierActionPerformed(evt);
            }
        });

        insertbutton.setText("Insert");
        insertbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttonActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Input Data Supplier Baru");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jalamat)
                    .addComponent(jsupplier)
                    .addComponent(jpenanggungjawab)
                    .addComponent(jkontak))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(namasupplier)
                    .addComponent(penanggungjawab)
                    .addComponent(kontak))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namasupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penanggungjawab, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jpenanggungjawab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkontak)
                    .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jalamat))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namasupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namasupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namasupplierActionPerformed

    private void insertbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttonActionPerformed
        // TODO add your handling code here:
        modelSupplier insert = new modelSupplier();
        controllerSupplier supp = new controllerSupplier();
        
        String Nama = namasupplier.getText();
        String Alamat = alamat.getText();
        String Penanggungjawab = penanggungjawab.getText();
        String Kontak = kontak.getText();
        
        insert.setNamaSupplier(Nama);
        insert.setAlamat(Alamat);
        insert.setKontak(Kontak);
        insert.setPenanggungJawab(Penanggungjawab);
        
        if(namasupplier.getText().length() >= 30)
        {
            JOptionPane.showMessageDialog(null, "Panjang Nama Maksimal 30 Huruf");
        }
        else if(alamat.getText().length() >= 30)
        {
            JOptionPane.showMessageDialog(null, "Panjang Nama Maksimal 30 Huruf");
        }
        else if(penanggungjawab.getText().length() >= 30)
        {
            JOptionPane.showMessageDialog(null, "Panjang Nama Maksimal 30 Huruf");
        }
        else if(kontak.getText().length() >= 15)
        {
            JOptionPane.showMessageDialog(null, "Nomor Handphone Tidak Boleh Lebih dari 15 Angka");
        }
        
        else if(namasupplier.getText().length() == 0 || alamat.getText().length() == 0 || penanggungjawab.getText().length() == 0 || kontak.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Semua Kolom Harus Diisi");
        }
        else
        {
            supp.insert(insert.getNamaSupplier(), insert.getAlamat(), insert.getPenanggungJawab(), insert.getKontak());  
        }
    }//GEN-LAST:event_insertbuttonActionPerformed

    
    
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton close;
    private javax.swing.JButton insertbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jalamat;
    private javax.swing.JLabel jkontak;
    private javax.swing.JLabel jpenanggungjawab;
    private javax.swing.JLabel jsupplier;
    private javax.swing.JTextField kontak;
    private javax.swing.JTextField namasupplier;
    private javax.swing.JTextField penanggungjawab;
    // End of variables declaration//GEN-END:variables
}
